# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: nginx_log
  path.config: "/usr/share/logstash/pipeline/nginx_log.conf"
  pipeline.workers: 1
- pipeline.id: mongodb_master_primary_slowquery_log
  path.config: "/usr/share/logstash/pipeline/mongodb_master_primary.conf"
- pipeline.id: mongodb_master_secondary_slowquery_log
  path.config: "/usr/share/logstash/pipeline/mongodb_master_secondary.conf"
- pipeline.id: mongodb_log_primary_slowquery_log
  path.config: "/usr/share/logstash/pipeline/mongodb_log_primary.conf"
- pipeline.id: mongodb_biglog_primary_slowquery_log
  path.config: "/usr/share/logstash/pipeline/mongodb_biglog_primary.conf"
